#!/usr/bin/env python3
"""Seed contractor master data into Supabase public.contractors table.

Populates all 45 audited Bulgarian commercial entities, EU cross-border partners,
and control benchmarks with official Commercial Register (ТР) and NRA VAT attributes.
"""

from __future__ import annotations

import json
import subprocess
import sys
from typing import Any

CONTRACTORS_DATA: list[dict[str, Any]] = [
    # 1. Main Recipient
    {
        "country_code": "BG",
        "eik": "208139865",
        "vat_number": "BG208139865",
        "legal_name": "„СИКРЕТ ЛЕДЖЪНД“ ЕООД",
        "trade_name": "Сикрет Леджънд",
        "legal_form": "ЕООД",
        "address": "гр. София, ж.к. Хаджи Димитър, бл. 34, ет. 5, ап. 25",
        "city": "София",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2025-01-23",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 100, ал. 1 ЗДДС",
        "ocr_aliases": ["Сикрет Леджънд ЕООД", "Сикрет Леджънд ООД", "Сикрет Леджънд ЕООД пц", "СИКРЕТ ЛЕДЖЪНД ЕООД"],
        "notes": "Основен получател на дружеството",
    },
    # 2. Key Supplier
    {
        "country_code": "BG",
        "eik": "208380135",
        "vat_number": "BG208380135",
        "legal_name": "„РМ КАСКАДА 2026“ ЕООД",
        "trade_name": "РМ Каскада",
        "legal_form": "ЕООД",
        "address": "гр. София, бул. Цариградско шосе 105",
        "city": "София",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2026-06-06",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 100, ал. 1 ЗДДС",
        "ocr_aliases": ["РМ Каскада 2026 ЕООД", "РМ КАСКАДА EООД", "РВМАЗРУК ЕООД", "РМ КАСКАДА 2026 ЕООД"],
        "notes": "Преименувано от РВМАЗРУК ЕООД през април 2026",
    },
    # 3. Fast Top Foods
    {
        "country_code": "BG",
        "eik": "207930830",
        "vat_number": None,
        "legal_name": "„ФАСТ ТОП ФУУДС“ ЕООД",
        "trade_name": "Фаст Топ Фуудс",
        "legal_form": "ЕООД",
        "address": "гр. Плевен, ул. Чаталджа 4",
        "city": "Плевен",
        "legal_status": "ACTIVE",
        "vat_status": "NOT_REGISTERED",
        "vat_registration_date": None,
        "vat_deregistration_date": None,
        "vat_legal_basis": None,
        "ocr_aliases": ["ФАСТ ТОП ФУУДС ЕООД", "ACT ТОП ФУУДС"],
        "notes": "Нерегистрирано по ЗДДС лице (NO NAME)",
    },
    # 4. GM 2025
    {
        "country_code": "BG",
        "eik": "208230838",
        "vat_number": None,
        "legal_name": "„ГМ 2025“ ЕООД",
        "trade_name": "ГМ 2025",
        "legal_form": "ЕООД",
        "address": "с. Горна Митрополия, ул. Никола Вапцаров 7",
        "city": "с. Горна Митрополия",
        "legal_status": "ACTIVE",
        "vat_status": "NOT_REGISTERED",
        "vat_registration_date": None,
        "vat_deregistration_date": None,
        "vat_legal_basis": None,
        "ocr_aliases": ["ГМ2025 ЕООД", "ГМ 2025 ЕООД"],
        "notes": "Получател по фактури на Валборген",
    },
    # 5. Metro Cash & Carry
    {
        "country_code": "BG",
        "eik": "121644736",
        "vat_number": "BG121644736",
        "legal_name": "„МЕТРО БЪЛГАРИЯ“ ЕООД",
        "trade_name": "Метро Кеш енд Кери",
        "legal_form": "ЕООД",
        "address": "гр. София, бул. Цариградско шосе 7-11 км",
        "city": "София",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "1999-03-01",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["МЕТРО КЕШ ЕНД КЕРИ БЪЛГАРИЯ ЕООД", "МЕТРО БЪЛГАРИЯ ООД", "METRO Cash & Carry", "МЕТРО БЪЛГАРИЯ ЕООД"],
        "notes": "Официално в ТР е ЕООД",
    },
    # 6. Detelina DP
    {
        "country_code": "BG",
        "eik": "114609507",
        "vat_number": "BG114609507",
        "legal_name": "„ДЕТЕЛИНА ДП“ ООД",
        "trade_name": "Детелина ДП",
        "legal_form": "ООД",
        "address": "гр. Плевен, ул. Г. С. Раковски 57",
        "city": "Плевен",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2005-11-04",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["ООД ДЕТЕЛИНА-ЛП", "ДЕТЕЛИНА-ДП ЕООД", "ДЕТЕЛИНА ЛП", "ДЕТЕЛИНА ДП", "ДЕТЕЛИНА ДП ООД"],
        "notes": "Правна форма ООД (не ЕООД); матричен печат ЛП -> ДП",
    },
    # 7. Kapina 71
    {
        "country_code": "BG",
        "eik": "114500333",
        "vat_number": "BG114500333",
        "legal_name": "„КАПИНА 71“ ООД",
        "trade_name": "Капина 71",
        "legal_form": "ООД",
        "mol_name": "Веселин Върбанов",
        "address": "гр. Плевен, ул. Дойран 45",
        "city": "Плевен",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2000-01-20",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["МОЛ ВЕСЕЛИН ВЪРБАНОВ", "КАПИНА 71", "Капина 71 ООД", "КАПИНА 71 ООД", "200924103"],
        "notes": "Реален ЕИК 114500333",
    },
    # 8. Econt Express
    {
        "country_code": "BG",
        "eik": "207839658",
        "vat_number": "BG207839658",
        "legal_name": "„ЕКОНТ ЕКСПРЕС“ АД",
        "trade_name": "Еконт",
        "legal_form": "АД",
        "address": "гр. Русе, бул. Славянски 16",
        "city": "Русе",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2024-05-21",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["Еконт Експрес АД", "конт Еконт Експрес АД", "Еконт Експрес ООД", "117047646", "207039698", "„ЕКОНТ ЕКСПРЕС“ АД"],
        "notes": "Преобразувано в АД през май 2024 с нов ЕИК 207839658",
    },
    # 9. Clean Systems
    {
        "country_code": "BG",
        "eik": "206088589",
        "vat_number": "BG206088589",
        "legal_name": "„КЛИЙН СИСТЕМС“ ООД",
        "trade_name": "Клийн Системс",
        "legal_form": "ООД",
        "address": "гр. Плевен, ул. Свети Сава 8",
        "city": "Плевен",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2020-05-07",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["Клийн Системс ООД", "Клийн Системс ЕООД", "КЛИЙН СИСТЕМС ООД"],
        "notes": "Официално в ТР е ООД",
    },
    # 10. Pigeon Express
    {
        "country_code": "BG",
        "eik": "208402914",
        "vat_number": "BG208402914",
        "legal_name": "„ПИГЕОН ЕКСПРЕС“ ЕООД",
        "trade_name": "Пигеон Експрес",
        "legal_form": "ЕООД",
        "address": "гр. Пловдив, ул. Орловец 9",
        "city": "Пловдив",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2025-07-17",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["Пигеон експрес ЕООД", "Пигеон експрес ООД", "ПИГЕОН ЕКСПРЕС ЕООД"],
        "notes": "Официално в ТР е ЕООД",
    },
    # 11. Cookielicious
    {
        "country_code": "BG",
        "eik": "207822235",
        "vat_number": "BG207822235",
        "legal_name": "„КУКИЛИШЪС“ ЕООД",
        "trade_name": "Кукилишъс",
        "legal_form": "ЕООД",
        "address": "гр. София, ул. Кестен 23",
        "city": "София",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2024-05-08",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["КУКИПИШС ЕООД", "Кукилишъс ЕООД", "КУКИЛИШЪС ЕООД"],
        "notes": "Поправен OCR шум КУКИПИШС",
    },
    # 12. Invictus Style
    {
        "country_code": "BG",
        "eik": "204540024",
        "vat_number": "BG204540024",
        "legal_name": "„ИНВИКТЪС СТАЙЛ“ ЕООД",
        "trade_name": "Инвиктъс Стайл",
        "legal_form": "ЕООД",
        "address": "гр. София",
        "city": "София",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2017-04-10",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["ВИКТЪС СТАЙЛ ЕООД", "Инвиктъс Стайл ЕООД", "ИНВИКТЪС СТАЙЛ ЕООД"],
        "notes": "Възстановено начално ИН от лого",
    },
    # 13. Orion - Kolev 2019
    {
        "country_code": "BG",
        "eik": "205525267",
        "vat_number": "BG205525267",
        "legal_name": "„ОРИОН - КОЛЕВ 2019“ ЕООД",
        "trade_name": "Орион - Колев",
        "legal_form": "ЕООД",
        "address": "гр. Плевен",
        "city": "Плевен",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2019-02-15",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["ОРИОН КОЛЕВ - ЕООД", "Орион Колев 2019 ЕООД", "ОРИОН - КОЛЕВ 2019 ЕООД"],
        "notes": "Годината 2019 отличава от старата фирма 203114751",
    },
    # 14. Corte Diletto
    {
        "country_code": "BG",
        "eik": "201851618",
        "vat_number": "BG201851618",
        "legal_name": "„КОРТЕ ДИЛЕТО“ ЕООД",
        "trade_name": "Корте Дилето",
        "legal_form": "ЕООД",
        "address": "гр. Елин Пелин",
        "city": "Елин Пелин",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2012-01-13",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["Корте Дилето ЕООД", "Корте Дилето ООД", "КОРТЕ ДИЛЕТО ЕООД"],
        "notes": "Официално в ТР е ЕООД",
    },
    # 15. Druzhestvo za Kasovi Uslugi AD
    {
        "country_code": "BG",
        "eik": "175327305",
        "vat_number": "BG175327305",
        "legal_name": "„ДРУЖЕСТВО ЗА КАСОВИ УСЛУГИ“ АД",
        "trade_name": "ДКУ АД",
        "legal_form": "АД",
        "address": "гр. София, ул. Иван Хаджийски",
        "city": "София",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2007-08-01",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["Дружество за касови услуги АД", "ДКУ АД"],
        "notes": "Инкасо услуги и касово обслужване",
    },
    # 16. Easypay AD
    {
        "country_code": "BG",
        "eik": "131344648",
        "vat_number": "BG131344648",
        "legal_name": "„ИЗИПЕЙ“ АД",
        "trade_name": "Easypay",
        "legal_form": "АД",
        "address": "гр. София, ул. Иван Вазов 16",
        "city": "София",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2009-02-02",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["ИЗИПЕЙ АД", "Easypay", "Изипей"],
        "notes": "Платежна институция",
    },
    # 17. Veselin Balev EOOD
    {
        "country_code": "BG",
        "eik": "114616366",
        "vat_number": "BG114616366",
        "legal_name": "„ВЕСЕЛИН БАЛЕВ“ ЕООД",
        "trade_name": "Веселин Балев",
        "legal_form": "ЕООД",
        "address": "гр. Плевен, ул. Дойран 63А",
        "city": "Плевен",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2003-05-15",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["ВЕСЕЛИН БАЛЕВ ЕООД", "ЕТ Веселин Балев", "Веселин Балев"],
        "notes": "Официално в ТР е ЕООД (не ЕТ)",
    },
    # 18. Tsvetna Radost OOD
    {
        "country_code": "BG",
        "eik": "200349655",
        "vat_number": "BG200349655",
        "legal_name": "„ЦВЕТНА РАДОСТ“ ООД",
        "trade_name": "Цветна Радост",
        "legal_form": "ООД",
        "address": "гр. София",
        "city": "София",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2009-01-27",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 100, ал. 1 ЗДДС",
        "ocr_aliases": ["ЦВЕТНА РАДОСТ - ООД", "Цветна Радост ООД"],
        "notes": None,
    },
    # 19. Vivacom Bulgaria EAD
    {
        "country_code": "BG",
        "eik": "831642181",
        "vat_number": "BG831642181",
        "legal_name": "„ВИВАКОМ БЪЛГАРИЯ“ ЕАД",
        "trade_name": "Vivacom",
        "legal_form": "ЕАД",
        "address": "гр. София, бул. Цариградско шосе 115и",
        "city": "София",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "1994-04-01",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["Виваком България ЕАД", "БТК ЕАД", "VIVACOM", "Българска телекомуникационна компания"],
        "notes": "Vivacom Bulgaria EAD",
    },
    # 20. A1 Bulgaria EAD
    {
        "country_code": "BG",
        "eik": "131468980",
        "vat_number": "BG131468980",
        "legal_name": "„А1 БЪЛГАРИЯ“ ЕАД",
        "trade_name": "A1",
        "legal_form": "ЕАД",
        "address": "гр. София, ул. Кукуш 1",
        "city": "София",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2005-08-01",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["Al България ЕАД", "А1 България ЕАД", "Мобилтел ЕАД", "A1 Bulgaria"],
        "notes": "Поправен OCR шум Al -> А1",
    },
    # 21. SBB Group OOD
    {
        "country_code": "BG",
        "eik": "131164568",
        "vat_number": "BG131164568",
        "legal_name": "„СББ ГРУП“ ООД",
        "trade_name": "СББ Груп",
        "legal_form": "ООД",
        "address": "гр. София, бул. България 102",
        "city": "София",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2004-02-10",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["Си Би Ес Груп ООД", "CBS Group", "СББ ГРУП ООД"],
        "notes": "В ТР е на кирилица СББ ГРУП (не CBS)",
    },
    # 22. Magnezia EOOD
    {
        "country_code": "BG",
        "eik": "114631464",
        "vat_number": "BG114631464",
        "legal_name": "„МАГНЕЗИЯ“ ЕООД",
        "trade_name": "Магнезия",
        "legal_form": "ЕООД",
        "address": "гр. Плевен, ж.к. Сторгозия",
        "city": "Плевен",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2006-03-20",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["МАГНЕЗИЯ ЕООД", "Магнезия"],
        "notes": "Стокова разписка без ЕИК - валидиран през ТР",
    },
    # 23. Gentleman Group EOOD
    {
        "country_code": "BG",
        "eik": "203818240",
        "vat_number": "BG203818240",
        "legal_name": "„ДЖЕНТЪЛМЕН ГРУП“ ЕООД",
        "trade_name": "Джентълмен Груп",
        "legal_form": "ЕООД",
        "address": "гр. София, бул. Патриарх Евтимий 77",
        "city": "София",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2015-12-03",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["ОЖЕНТЪЛМЕН ГРУГ oy", "Джентълмен Груп", "Gentleman Group"],
        "notes": "Шум от термопечат възстановен",
    },
    # 24. Absolut Plus OOD
    {
        "country_code": "BG",
        "eik": "131433901",
        "vat_number": "BG131433901",
        "legal_name": "„АБСОЛЮТ ПЛЮС“ ООД",
        "trade_name": "Абсолют Плюс",
        "legal_form": "ООД",
        "address": "гр. София, ул. Люботрън 3-5-7",
        "city": "София",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2006-05-15",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["АБСОЛЮТ ПЛЮС ООД", "Абсолют Плюс Еоод"],
        "notes": "В ТР е ООД (не ЕООД)",
    },
    # 25. Murgash 88 OOD
    {
        "country_code": "BG",
        "eik": "203012369",
        "vat_number": "BG203012369",
        "legal_name": "„МУРГАШ 88“ ООД",
        "trade_name": "Мургаш 88",
        "legal_form": "ООД",
        "address": "с. Гурмазово, общ. Божурище, ул. Гурмазовско шосе 82",
        "city": "с. Гурмазово",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2014-04-08",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["Мургаш 88 ООД"],
        "notes": None,
    },
    # 26. Arpak EOOD
    {
        "country_code": "BG",
        "eik": "114690224",
        "vat_number": "BG114690224",
        "legal_name": "„АРПАК“ ЕООД",
        "trade_name": "Арпак",
        "legal_form": "ЕООД",
        "address": "гр. Плевен, ул. Сан Стефано 47А",
        "city": "Плевен",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2007-09-12",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["Арпак ЕООД"],
        "notes": None,
    },
    # 27. Optisprint OOD
    {
        "country_code": "BG",
        "eik": "114548965",
        "vat_number": "BG114548965",
        "legal_name": "„ОПТИСПРИНТ“ ООД",
        "trade_name": "Оптиспринт",
        "legal_form": "ООД",
        "address": "гр. Плевен, ул. Гоце Делчев",
        "city": "Плевен",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2004-04-23",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["ONTUCNPUHT O00", "Оптиспринт ООД", "Optisprint"],
        "notes": "Поправен OCR шум от термопечат",
    },
    # 28. Press and Fresh OOD
    {
        "country_code": "BG",
        "eik": "200875744",
        "vat_number": "BG200875744",
        "legal_name": "„ПРЕС ЕНД ФРЕШ“ ООД",
        "trade_name": "Прес енд Фреш",
        "legal_form": "ООД",
        "address": "гр. София, ул. Опорска река 3",
        "city": "София",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2016-08-10",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["ПРЕС ЕНД ФРЕШ ООД", "Press & Fresh"],
        "notes": None,
    },
    # 29. Tim Stok 23 OOD
    {
        "country_code": "BG",
        "eik": "207390964",
        "vat_number": "BG207390964",
        "legal_name": "„ТИМ СТОК 23“ ООД",
        "trade_name": "Тим Сток 23",
        "legal_form": "ООД",
        "address": "гр. Лясковец, ул. Оборище 9",
        "city": "Лясковец",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2024-01-10",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["Тим Сток 23 ООД"],
        "notes": None,
    },
    # 30. Kaem 89 EOOD
    {
        "country_code": "BG",
        "eik": "203197380",
        "vat_number": "BG203197380",
        "legal_name": "„КАЕМ 89“ ЕООД",
        "trade_name": "Каем 89",
        "legal_form": "ЕООД",
        "address": "гр. Плевен, ул. Стоян Михайловски",
        "city": "Плевен",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2016-11-23",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["Каем 89 - ЕООД", "Каем 89 ЕООД"],
        "notes": None,
    },
    # 31. Lidl Bulgaria KD
    {
        "country_code": "BG",
        "eik": "131071587",
        "vat_number": "BG131071587",
        "legal_name": "„ЛИДЛ БЪЛГАРИЯ ЕООД ЕНД КО“ КД",
        "trade_name": "Лидл",
        "legal_form": "КД",
        "address": "с. Равно поле, ул. 3-та № 1",
        "city": "с. Равно поле",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2003-03-24",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["Лидл България ЕООД енд КО КД", "131071687", "Lidl"],
        "notes": "Поправен шум от сканиране 131071687",
    },
    # 32. Kaufland Bulgaria KD
    {
        "country_code": "BG",
        "eik": "131129282",
        "vat_number": "BG131129282",
        "legal_name": "„КАУФЛАНД БЪЛГАРИЯ ЕООД ЕНД КО“ КД",
        "trade_name": "Кауфланд",
        "legal_form": "КД",
        "address": "гр. София, ул. Скопие 1А",
        "city": "София",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2003-10-01",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["Кауфланд България ЕООД енд Ко КД", "Kaufland"],
        "notes": None,
    },
    # 33. Praktiker Retail EOOD
    {
        "country_code": "BG",
        "eik": "200525782",
        "vat_number": "BG200525782",
        "legal_name": "„ПРАКТИКЕР РИТЕЙЛ“ ЕООД",
        "trade_name": "Практикер",
        "legal_form": "ЕООД",
        "address": "гр. София, бул. Околовръстен път 265",
        "city": "София",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2008-05-15",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["ПРАКТИКЕР PATE ЕООД", "Практикер", "Практикер Ритейл"],
        "notes": "Поправен дефект PATE -> РИТЕЙЛ",
    },
    # 34. Valborgen OOD
    {
        "country_code": "BG",
        "eik": "114609731",
        "vat_number": "BG114609731",
        "legal_name": "„ВАЛБОРГЕН“ ООД",
        "trade_name": "Валборген",
        "legal_form": "ООД",
        "address": "гр. Плевен, ул. Гренадирска 116",
        "city": "Плевен",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2008-08-19",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["Валборген ООД", "Валборген"],
        "notes": None,
    },
    # 35. Temenuzhka Kocheva - Nadya ET
    {
        "country_code": "BG",
        "eik": "824156453",
        "vat_number": "BG824156453",
        "legal_name": "„ТЕМЕНУЖКА КОЧЕВА - НАДЯ“ ЕТ",
        "trade_name": "Теменужка Кочева",
        "legal_form": "ЕТ",
        "address": "гр. Плевен",
        "city": "Плевен",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "1995-11-22",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["ЕТ Теменужка Кочева Надя", "Теменужка Кочева"],
        "notes": "Едноличен търговец",
    },
    # 36. O Skari OOD
    {
        "country_code": "BG",
        "eik": "114598204",
        "vat_number": "BG114598204",
        "legal_name": "„О СКАРИ“ ООД",
        "trade_name": "О Скари",
        "legal_form": "ООД",
        "address": "гр. Плевен",
        "city": "Плевен",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2002-04-10",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["О скари ООД"],
        "notes": None,
    },
    # 37. Anda 2012 EOOD
    {
        "country_code": "BG",
        "eik": "202262252",
        "vat_number": "BG202262252",
        "legal_name": "„АНДА 2012 - АНКО ПЕТРОВ“ ЕООД",
        "trade_name": "Анда 2012",
        "legal_form": "ЕООД",
        "address": "гр. Плевен",
        "city": "Плевен",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2012-10-09",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["Анда 2012 Анко Петров ЕООД"],
        "notes": None,
    },
    # 38. N and V OOD
    {
        "country_code": "BG",
        "eik": "114681129",
        "vat_number": "BG114681129",
        "legal_name": "„Н ЕНД В“ ООД",
        "trade_name": "Н енд В",
        "legal_form": "ООД",
        "address": "гр. Плевен, ул. Х. Димитър 53-55",
        "city": "Плевен",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2008-06-10",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 100, ал. 1 ЗДДС",
        "ocr_aliases": ["НендВ ООД", "Н и В ООД"],
        "notes": "Разделено изписване Н ЕНД В",
    },
    # 39. Grestokomers EOOD
    {
        "country_code": "BG",
        "eik": "104586266",
        "vat_number": "BG104586266",
        "legal_name": "„ГРЕСТОКОМЕРС“ ЕООД",
        "trade_name": "Грестокомерс",
        "legal_form": "ЕООД",
        "address": "гр. Велико Търново",
        "city": "Велико Търново",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2002-07-01",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["Грестокомерс ЕООД"],
        "notes": None,
    },
    # 40. Express Security SOD EOOD
    {
        "country_code": "BG",
        "eik": "114540185",
        "vat_number": "BG114540185",
        "legal_name": "„ЕКСПРЕС СЕКЮРИТИ СОД“ ЕООД",
        "trade_name": "Експрес Секюрити СОД",
        "legal_form": "ЕООД",
        "address": "гр. Плевен",
        "city": "Плевен",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2001-02-07",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["Експрес Секюрити СОД ЕООД"],
        "notes": None,
    },
    # 41. Intermes OOD
    {
        "country_code": "BG",
        "eik": "114598690",
        "vat_number": "BG114598690",
        "legal_name": "„ИНТЕРМЕС“ ООД",
        "trade_name": "Интермес",
        "legal_form": "ООД",
        "address": "гр. Плевен",
        "city": "Плевен",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2002-05-15",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["Интермес ООД"],
        "notes": None,
    },
    # 42. ViK Pleven EOOD
    {
        "country_code": "BG",
        "eik": "824106518",
        "vat_number": "BG824106518",
        "legal_name": "„ВОДОСНАБДЯВАНЕ И КАНАЛИЗАЦИЯ“ ЕООД",
        "trade_name": "ВиК Плевен",
        "legal_form": "ЕООД",
        "address": "гр. Плевен, ул. Сан Стефано 25",
        "city": "Плевен",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "1994-04-01",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["ВиК ЕООД", "ВиК гр. Плевен", "Водоснабдяване и канализация"],
        "notes": "Пълно официално наименование от ТР",
    },
    # 43. Gaudi DS EOOD
    {
        "country_code": "BG",
        "eik": "201021273",
        "vat_number": "BG201021273",
        "legal_name": "„ГАУДИ ДИ ЕС“ ЕООД",
        "trade_name": "Гауди Ди Ес",
        "legal_form": "ЕООД",
        "address": "гр. София",
        "city": "София",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2010-01-26",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["ГАУДИ ДИ ЕС ЕООД"],
        "notes": "Товарителница 17.pdf",
    },
    # 44. Euro Pest EOOD
    {
        "country_code": "BG",
        "eik": "175307726",
        "vat_number": "BG175307726",
        "legal_name": "„ЕВРО ПЕСТ“ ЕООД",
        "trade_name": "Евро Пест",
        "legal_form": "ЕООД",
        "address": "гр. София",
        "city": "София",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2025-11-01",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["ЕВРО ПЕСТ ЕООД"],
        "notes": "Разписка 23.pdf",
    },
    # 45. Toplivo Gaz EOOD
    {
        "country_code": "BG",
        "eik": "130864186",
        "vat_number": "BG130864186",
        "legal_name": "„ТОПЛИВО ГАЗ“ ЕООД",
        "trade_name": "Топливо Газ",
        "legal_form": "ЕООД",
        "address": "гр. София, ул. Солунска 2",
        "city": "София",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2003-09-18",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["Топливо Газ ЕООД"],
        "notes": None,
    },
    # 46. Eliko 143 EOOD
    {
        "country_code": "BG",
        "eik": "114682544",
        "vat_number": "BG114682544",
        "legal_name": "„ЕЛИКО 143“ ЕООД",
        "trade_name": "Елико 143",
        "legal_form": "ЕООД",
        "address": "гр. Плевен, ж.к. Дружба",
        "city": "Плевен",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2007-06-12",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": ["ЕЛИКО 143ЕОД", "Елико 143 ЕООД", "206587399"],
        "notes": "Реален ЕИК 114682544",
    },
    # EU Cross-Border Partners
    {
        "country_code": "IE",
        "eik": "6388047V",
        "vat_number": "IE6388047V",
        "legal_name": "GOOGLE CLOUD EMEA LIMITED",
        "trade_name": "Google Cloud",
        "legal_form": "LTD",
        "address": "70 SIR JOHN ROGERSON'S QUAY, DUBLIN 2, IRELAND",
        "city": "Dublin",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2008-01-01",
        "vat_deregistration_date": None,
        "vat_legal_basis": "VIES EU Reverse Charge",
        "ocr_aliases": ["Google Cloud EMEA Limited", "Google Ireland", "Google"],
        "notes": "VIES verified",
    },
    {
        "country_code": "IE",
        "eik": "9692928F",
        "vat_number": "IE9692928F",
        "legal_name": "META PLATFORMS IRELAND LIMITED",
        "trade_name": "Meta / Facebook",
        "legal_form": "LTD",
        "address": "4 GRAND CANAL SQUARE, GRAND CANAL HARBOUR, DUBLIN 2, IRELAND",
        "city": "Dublin",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2009-03-15",
        "vat_deregistration_date": None,
        "vat_legal_basis": "VIES EU Reverse Charge",
        "ocr_aliases": ["Meta Platforms Ireland Limited", "Facebook Ireland", "Meta"],
        "notes": "VIES verified",
    },
    {
        "country_code": "IE",
        "eik": "4523315Q",
        "vat_number": "IE4523315Q",
        "legal_name": "ADOBE SYSTEMS SOFTWARE IRELAND LIMITED",
        "trade_name": "Adobe",
        "legal_form": "LTD",
        "address": "4-6 RIVERWALK, CITYWEST BUSINESS CAMPUS, DUBLIN 24, IRELAND",
        "city": "Dublin",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2005-06-20",
        "vat_deregistration_date": None,
        "vat_legal_basis": "VIES EU Reverse Charge",
        "ocr_aliases": ["Adobe Systems Software Ireland Limited", "Adobe Ireland", "Adobe"],
        "notes": "VIES verified",
    },
    {
        "country_code": "LU",
        "eik": "20260743",
        "vat_number": "LU20260743",
        "legal_name": "AMAZON EU SARL / AWS",
        "trade_name": "Amazon Web Services / AWS",
        "legal_form": "SARL",
        "address": "38 AVENUE JOHN F. KENNEDY, L-1855 LUXEMBOURG",
        "city": "Luxembourg",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2003-08-01",
        "vat_deregistration_date": None,
        "vat_legal_basis": "VIES EU Reverse Charge",
        "ocr_aliases": ["Amazon EU S.a.r.l.", "AWS", "Amazon Web Services"],
        "notes": "VIES verified",
    },
    # Control Benchmarks
    {
        "country_code": "BG",
        "eik": "111111113",
        "vat_number": "BG111111113",
        "legal_name": "„ФАЛИРАЛА КОМПАНИЯ“ ЕООД",
        "trade_name": "Фалирала Компания",
        "legal_form": "ЕООД",
        "address": "гр. София, ул. Търговска 1",
        "city": "София",
        "legal_status": "BANKRUPTCY",
        "vat_status": "DEREGISTERED",
        "vat_registration_date": "2015-01-01",
        "vat_deregistration_date": "2024-12-31",
        "vat_legal_basis": "чл. 107, т. 1 ЗДДС",
        "ocr_aliases": [],
        "notes": "Тестов бенчмарк: Фалит / Дерегистрирано лице",
    },
    {
        "country_code": "BG",
        "eik": "222222226",
        "vat_number": "BG222222226",
        "legal_name": "„ЗАЛИЧЕН ТЪРГОВЕЦ“ ООД",
        "trade_name": "Заличен Търговец",
        "legal_form": "ООД",
        "address": "гр. Пловдив, бул. Марица 5",
        "city": "Пловдив",
        "legal_status": "DEREGISTERED",
        "vat_status": "DEREGISTERED",
        "vat_registration_date": "2018-05-10",
        "vat_deregistration_date": "2025-06-30",
        "vat_legal_basis": "чл. 107, т. 2 ЗДДС",
        "ocr_aliases": [],
        "notes": "Тестов бенчмарк: Заличен от Търговския регистър",
    },
    {
        "country_code": "BG",
        "eik": "333333339",
        "vat_number": "BG333333339",
        "legal_name": "„НОВОРЕГИСТРИРАНА ФИРМА“ ЕООД",
        "trade_name": "Новорегистрирана Фирма",
        "legal_form": "ЕООД",
        "address": "гр. Варна, ул. Славянска 10",
        "city": "Варна",
        "legal_status": "ACTIVE",
        "vat_status": "REGISTERED",
        "vat_registration_date": "2026-08-20",
        "vat_deregistration_date": None,
        "vat_legal_basis": "чл. 96 ЗДДС",
        "ocr_aliases": [],
        "notes": "Тестов бенчмарк: Регистрация по време на данъчни събития",
    },
    {
        "country_code": "BG",
        "eik": "444444441",
        "vat_number": None,
        "legal_name": "„НЕОБЛАГАЕМА ДРЕБНА ФИРМА“ ЕООД",
        "trade_name": "Необлагаема Дребна Фирма",
        "legal_form": "ЕООД",
        "address": "гр. Бургас, ул. Александровска 12",
        "city": "Бургас",
        "legal_status": "ACTIVE",
        "vat_status": "NOT_REGISTERED",
        "vat_registration_date": None,
        "vat_deregistration_date": None,
        "vat_legal_basis": None,
        "ocr_aliases": [],
        "notes": "Тестов бенчмарк: Дребна фирма без ДДС",
    },
]


def generate_sql() -> str:
    """Generate SQL INSERT statements for PostgreSQL with ON CONFLICT UPDATE."""
    lines = [
        "BEGIN;",
        "-- Bulk upsert contractors master data",
    ]

    for item in CONTRACTORS_DATA:
        country_code = item["country_code"]
        eik = item["eik"]
        vat_number = f"'{item['vat_number']}'" if item["vat_number"] else "NULL"
        legal_name = item["legal_name"].replace("'", "''")
        trade_name = f"'{item['trade_name'].replace('\'', '\'\'')}'" if item["trade_name"] else "NULL"
        legal_form = f"'{item['legal_form']}'" if item["legal_form"] else "NULL"
        mol_name = f"'{item['mol_name'].replace('\'', '\'\'')}'" if item.get("mol_name") else "NULL"
        address = f"'{item['address'].replace('\'', '\'\'')}'" if item["address"] else "NULL"
        city = f"'{item['city'].replace('\'', '\'\'')}'" if item["city"] else "NULL"
        legal_status = item["legal_status"]
        vat_status = item["vat_status"]
        vat_reg_date = f"'{item['vat_registration_date']}'" if item["vat_registration_date"] else "NULL"
        vat_dereg_date = f"'{item['vat_deregistration_date']}'" if item["vat_deregistration_date"] else "NULL"
        vat_legal_basis = f"'{item['vat_legal_basis'].replace('\'', '\'\'')}'" if item["vat_legal_basis"] else "NULL"
        
        # Format ocr_aliases as postgres text[]
        escaped_aliases = [alias.replace("'", "''") for alias in item["ocr_aliases"]]
        if escaped_aliases:
            aliases_sql = "ARRAY[" + ", ".join(f"'{a}'" for a in escaped_aliases) + "]::text[]"
        else:
            aliases_sql = "'{}'::text[]"

        notes = f"'{item['notes'].replace('\'', '\'\'')}'" if item.get("notes") else "NULL"

        sql = f"""
INSERT INTO public.contractors (
    country_code, eik, vat_number, legal_name, trade_name,
    legal_form, mol_name, address, city, legal_status,
    vat_status, vat_registration_date, vat_deregistration_date,
    vat_legal_basis, is_verified, verified_source, ocr_aliases, notes
) VALUES (
    '{country_code}', '{eik}', {vat_number}, '{legal_name}', {trade_name},
    {legal_form}, {mol_name}, {address}, {city}, '{legal_status}',
    '{vat_status}', {vat_reg_date}, {vat_dereg_date},
    {vat_legal_basis}, true, 'COMMERCIAL_REGISTER', {aliases_sql}, {notes}
)
ON CONFLICT (country_code, eik) DO UPDATE SET
    vat_number = EXCLUDED.vat_number,
    legal_name = EXCLUDED.legal_name,
    trade_name = EXCLUDED.trade_name,
    legal_form = EXCLUDED.legal_form,
    mol_name = COALESCE(EXCLUDED.mol_name, public.contractors.mol_name),
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    legal_status = EXCLUDED.legal_status,
    vat_status = EXCLUDED.vat_status,
    vat_registration_date = EXCLUDED.vat_registration_date,
    vat_deregistration_date = EXCLUDED.vat_deregistration_date,
    vat_legal_basis = EXCLUDED.vat_legal_basis,
    ocr_aliases = EXCLUDED.ocr_aliases,
    notes = EXCLUDED.notes,
    updated_at = now();
"""
        lines.append(sql.strip())

    lines.append("COMMIT;")
    lines.append("NOTIFY pgrst, 'reload schema';")
    return "\n".join(lines)


def main() -> None:
    sql_script = generate_sql()
    target_file = "/tmp/seed_contractors.sql"
    with open(target_file, "w", encoding="utf-8") as f:
        f.write(sql_script)

    print(f"Generated seed SQL script with {len(CONTRACTORS_DATA)} contractors.")
    
    # Execute on remote macmini-primary via SSH
    cmd = f"ssh diokarabaz@10.0.25.205 'docker exec -i supabase-db psql -U postgres -d postgres' < {target_file}"
    print("Executing migration on supabase-db...")
    res = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    if res.returncode != 0:
        print("Error executing SQL:", res.stderr)
        sys.exit(1)
    
    print("Success! Output:", res.stdout.strip()[:200])


if __name__ == "__main__":
    main()
